secret_key = "d34f62a5450bed73cb1a5bd750bce5c56c2cad63be59e4e83f7565f33fec30b3"

[database]
url = "sqlite://db.sqlite3?mode=rwc"

[auth_backend]
type = "database"

[middlewares]
live_reload.enabled = true

[static_files]
rewrite = "query_param"
cache_timeout = "1year"

[middlewares.session]
secure = false
